var sys_list =
{
'Achenar': 'Eridani',
'Adriel Prime': 'Proxima',
'Aganju': '61 Cygni',
'Akerons Gate': 'Sol',
'Altair III': 'Altair',
'Antares Frontier': 'Antares',
'Aragoth Prime': 'Aragoth',
'Arduinne': 'Tau Ceti',
'Arduinne Gas Cloud': 'Tau Ceti',
'Ardus': 'Aquitaine',
'Ashlan\'s Veil': 'Sulani',
'Asteroid Belt Alpha': 'Sol',
'Asteroid Belt Beta': 'Sol',
'Asteroid Belt Gamma': 'Sol',
'Bayanni': '61 Cygni',
'Blackbeards Wake': 'Smugglers Run',
'Callisto Basic Training Yard': 'Sol',
'Carpenter': 'Beta Hydri',
'Cassiopeia\'s Belt': 'Eridani',
'Ceres/Thule ': 'Sol',
'Chandilar': 'Eridani',
'Chandilar Planet': 'Eridani',
'Charis Duo': 'Antares',
'Cooper': 'Beta Hydri',
'Dahin': 'Capella',
'Dahin Mining Interest': 'Capella',
'der Todesengel': 'Alpha Centauri',
'Earth': 'Sol',
'Earth Basic Training Yard': 'Sol',
'Endriago': 'Gallina',
'Equatorial Earth': 'Sol',
'Eshu': '61 Cygni',
'Europa': 'Sol',
'Fenris': 'Aragoth',
'Freya': 'Aragoth',
'Gamma Sulani Planet': 'Sulani',
'Ganymede': 'Sol',
'GETCo Ruins': 'Gallina',
'Glenn': 'Beta Hydri',
'Glenn - DELET': 'Beta Hydri',
'Glorys Orbit': 'Beta Hydri',
'Grissom': 'Beta Hydri',
'Grissom Meteorological Site ': 'Beta Hydri',
'High Earth': 'Sol',
'Inverness': 'Tau Ceti',
'Inverness Down': 'Tau Ceti',
'Io': 'Sol',
'Ishuan': 'Castor',
'Ishuan Gas Giant': 'Castor',
'Jagerstadt': 'Alpha Centauri',
'Jotunheim': 'Aragoth',
'Jupiter': 'Sol',
'Kailaasa': 'Capella',
'Kasdreya\'s Weil': 'Antares',
'Kitara\'s Veil': 'Capella',
'Kokoyuko Moon': 'Antares',
'Kor Scorpius': 'Antares',
'Kor Vanaan': 'Antares',
'Kor Vanaan Planet': 'Antares',
'Lagarto': 'Gallina',
'Loch Mar': 'Proxima',
'Luna': 'Sol',
'Margesi': 'Proxima',
'Mars': 'Sol',
'Mars Alpha': 'Sol',
'Mars Basic Training Yard': 'Sol',
'Mars Beta': 'Sol',
'Mars Gamma': 'Sol',
'Mazzaroth Maelstrom': 'Sirius',
'Menog Swarm': '61 Cygni',
'Menorb': 'Castor',
'Menorb Planet': 'Castor',
'Mercury': 'Sol',
'Mondara Maelstrom': 'Vega',
'Mordane\'s Wake': 'Eidenmist',
'Moto - Do Not Delete, Or You Will Die!': '61 Cygni',
'Muspelheim': 'Aragoth',
'Nastrand Vor': 'Altair',
'Nastrand Vor Planet': 'Altair',
'Nebiros': 'Castor',
'Nebiros Planet': 'Castor',
'Nebulous': 'Sol',
'Neptune': 'Sol',
'New Edinburgh': 'Tau Ceti',
'Nifleheim Cloud': 'Aragoth',
'Odin Rex': 'Aragoth',
'Odins Belt': 'Aragoth',
'Ogun': '61 Cygni',
'Oricha Nla': '61 Cygni',
'Oya': '61 Cygni',
'Paramis': 'Smugglers Run',
'Pluto and Charon': 'Sol',
'Porvenir Mons Area': 'Gallina',
'Praetorium Mons Area (Planet Primus)': 'Vega',
'Primus': 'Vega',
'Ragnarok': 'Aragoth',
'Roc': 'Deneb',
'Roc 1': 'Deneb',
'Sandcastle': 'Castor',
'Saturn': 'Sol',
'Shepard': 'Beta Hydri',
'Shield': 'Beta Hydri',
'Sho\'da\'kan Nebula': 'Smugglers Run',
'Sho\'da\'kan Planet': 'Smugglers Run',
'Slayton': 'Beta Hydri',
'Spear': 'Beta Hydri',
'Sulani Highport': 'Sulani',
'Swooping Eagle': 'Sirius',
'Sword': 'Beta Hydri',
'Tarsis': 'Vega',
'Test Sector': 'Deep Space',
'Test Sector 1': 'Antares',
'Thelugi Rift': '61 Cygni',
'Unknown Galaxy ': 'Beta Hydri',
'Uranus': 'Sol',
'Valkyrie Twins': 'Aragoth',
'Varens Girdle': 'Aragoth',
'Venus': 'Sol',
'Vishao\'s Cove': 'Capella',
'Volundar Gap': 'Antares',
'Witberg': 'Alpha Centauri',
'Xipe Totec': 'Sirius',
'Yasuragi Area ': 'Sirius',
'Yemaha': '61 Cygni',
'Yokan': 'Capella',
'Zuri Maji': '61 Cygni',
'Zweihander': 'Alpha Centauri',
}
